max_width = 80
normalize_comments = true
imports_indent = "Block"
imports_layout = "HorizontalVertical"
imports_granularity="Crate"
combine_control_expr = false
force_multiline_blocks = true
trailing_semicolon = false
edition = "2021"
use_try_shorthand = true
use_field_init_shorthand = true
